name = "githus-b2b"
compatibility_date = "2025-06-01"
assets.directory = "./"
dev.port = 3000
routes = [
  { pattern = "githus.com", custom_domain = true },
  { pattern = "www.githus.com", custom_domain = true }
]
